services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./back-end/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    container_name: api
    build: ./back-end
    ports:
      - 5000:5000 # WORLD:CONTAINER
    env_file:
      - ./back-end/.env
    depends_on:
      - postgres

  spa:
    container_name: spa
    build: ./front-end
    volumes:
      - react-volume:/var/www/html

  openssl:
    build: ./openssl
    volumes:
      - ssl-certs:/certs

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - react-volume:/var/www/html
      - ssl-certs:/certs
    depends_on:
      - postgres
      - api
      - spa
      - openssl

volumes:
  postgres-data:
  react-volume:
  ssl-certs:
